### ISSUE TITLE
Reproducing the results

### ISSUE THREAD

**Issue by alooow** [kiaraesguerra/SAO-ECO#1]
Hi there!

I was wondering how can I reproduce the results from the paper? Or, in the minimal example, just run the command provided in README. In the current state of the repository, it crashes with an error

**Comment by kiaraesguerra** [comment]
Hello!

It should be possible to reproduce the results from the repository. May I
know what the error is? I will try running it too to see what’s wrong.
Thank you!

**Comment by kiaraesguerra** [comment]
Fixed some bugs, can now run delta, sao-delta, eco, and sao-eco

**Comment by kiaraesguerra** [comment]
Hi!

I've just found that there are a lot of issues with the repository.
I've fixed them now. Sorry about that!

Here's a notebook with sample experiments:
https://colab.research.google.com/drive/1O47ZD5RT3sYg3uuixs6f-2MO0-9J7AMe?usp=sharing

**Comment by alooow** [comment]
Thanks, it's working now!
